# Generated by Django 4.1.2 on 2022-10-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_level_topic_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
                ('answer_1', models.CharField(max_length=50)),
                ('checks', models.BooleanField()),
            ],
        ),
    ]
