# Generated by Django 4.1.2 on 2022-10-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_multiplechoice_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoice',
            name='correct_answer',
            field=models.CharField(choices=[('1', '1. answer'), ('2', '2. answer'), ('3', '3. answer'), ('4', '4. answer')], max_length=10, null=True),
        ),
    ]
