# Generated by Django 4.1.2 on 2022-10-20 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_multiplechoice_correct_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='chapters',
        ),
        migrations.AddField(
            model_name='topic',
            name='start_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.chapter'),
        ),
    ]
