# Generated by Django 4.1.2 on 2022-10-20 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_topic_chapters_topic_start_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_chapter', to='base.chapter'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='prev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_chapter', to='base.chapter'),
        ),
    ]
