# Generated by Django 4.1.2 on 2022-10-20 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_chapter_next_chapter_prev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='start_chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.chapter'),
        ),
    ]
