# Generated by Django 4.1.2 on 2022-10-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_topic_start_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='base.category'),
        ),
    ]
