# Generated by Django 4.1.2 on 2022-10-20 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_topic_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='categories',
        ),
        migrations.AddField(
            model_name='topic',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.category'),
            preserve_default=False,
        ),
    ]
